<a href="https://colab.research.google.com/github/singh-damanpreet04/6_months_training/blob/main/python/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Q1 Create a 1D Numpy array “a” containing 10 random integers between 0 and 99.**

In [ ]:
a = np.random.randint(0,99,size = 10)
a

array([68, 63, 14, 67, 20, 79, 60, 74, 93, 35])

**Q2 Create a 2D Numpy array “b” of shape (3, 4) containing random integers between -10 and 10.**

In [ ]:
b = np.random.randint(-10,10,size=12).reshape(3,4)
b

array([[  2,  -7,  -9,  -7],
       [ -7,   8, -10,   2],
       [  1,   1,  -7,  -9]])

**Q3  Reshape “b” into a 1D Numpy array “b_flat”.**

In [ ]:
b.flatten()
# arr2.reshape(1,12)

array([  2,  -7,  -9,  -7,  -7,   8, -10,   2,   1,   1,  -7,  -9])

***Q4 Create a copy of “a” called “a_copy”, and set the first element of “a_copy” to -1***

In [ ]:
a_copy = a.copy()
a_copy[0] = -1
print(a_copy)
print(a)

[-1 63 14 67 20 79 60 74 93 35]
[68 63 14 67 20 79 60 74 93 35]


**Q5  Create a 1D Numpy array “c” containing every second element of “a”.**

In [ ]:
c = a[::2]
c

array([68, 14, 20, 60, 93])

**Q6 Print the third element of “a”.**

In [ ]:
print(a)
print(a[2])

[68 63 14 67 20 79 60 74 93 35]
14


**Q7 Print the last element of “b”.**

In [ ]:
print(b)
print("\n")
b[-1]

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]]




array([ 1,  1, -7, -9])

**Q8 Print the first two rows and last two columns of “b”.**

In [ ]:
b[:2, -2:]

array([[ -9,  -7],
       [-10,   2]])

**Q9 Assign the second row of “b” to a variable called “b_row”.**

In [ ]:
print(b)
print("\n")
b_row = b[1]
b_row

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]]




array([ -7,   8, -10,   2])

**Q10 Assign the first column of “b” to a variable called “b_col”.**

In [ ]:
print(b)
print("\n")
b_col = b[:,0]
b_col

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]]




array([ 2, -7,  1])

**Q11 Create a 1D Numpy array “d” containing the integers from 1 to 10.**

In [ ]:
d = np.linspace(1,10,10, dtype="int")
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Q12  Add “a” and “d” element-wise to create a new Numpy array “e”.Multiply “b” by 2 to create a new Numpy array “b_double”.**

In [ ]:
print(a,'\n')
print(d,'\n')
e = a+d
e

[68 63 14 67 20 79 60 74 93 35] 

[ 1  2  3  4  5  6  7  8  9 10] 



array([ 69,  65,  17,  71,  25,  85,  67,  82, 102,  45])

**Q12  Add “a” and “d” element-wise to create a new Numpy array “e”.Multiply “b” by 2 to create a new Numpy array “b_double”.**

In [ ]:
print(b,'\n')
# b_double = b*2
b_double = np.multiply(b,2)
b_double

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]] 



array([[  4, -14, -18, -14],
       [-14,  16, -20,   4],
       [  2,   2, -14, -18]])

**Q13  Calculate the dot product of “b” and “b_double” to create a new Numpy array “f”.**

In [ ]:
print(b,'\n\n',b_double,'\n\n')
f = np.dot(b,b_double.transpose())
f

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]] 

 [[  4 -14 -18 -14]
 [-14  16 -20   4]
 [  2   2 -14 -18]] 




array([[366,  12, 242],
       [ 12, 434, 106],
       [242, 106, 264]])

**Q14 Calculate the mean of “a”,” b”, and “b_double” to create a new Numpy array “g”.**

In [ ]:
a_mean = np.mean(a)
b_mean = np.mean(b)
b_double_mean = np.mean(b_double)

print(a_mean)
print(b_mean)
print(b_double_mean)

print('\n')

g = np.array([a_mean,b_mean,b_double_mean])
g

57.3
-3.5
-7.0




array([57.3, -3.5, -7. ])

**Q15 Find the sum of every element in “a” and assign it to a variable “a_sum”.**

In [ ]:
a_sum = np.sum(a)
# for num in a:
#   a_sum += num
print(a_sum)

573


**Q16 Find the minimum element in “b” and assign it to a variable “b_min”.**

In [ ]:
print(b,"\n")
b_min = np.min(b)
b_min

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]] 



np.int64(-10)

**Q17 Find the maximum element in “b_double” and assign it to a variable “b_double_max”.**

In [ ]:
print(b_double,'\n')
b_double_max = np.max(b_double)
b_double_max

[[  4 -14 -18 -14]
 [-14  16 -20   4]
 [  2   2 -14 -18]] 



np.int64(16)