<a href="https://colab.research.google.com/github/singh-damanpreet04/6_months_training/blob/main/python/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import numpy as np

**Q1**

In [103]:
a = np.random.randint(0,99,size = 10)
a

array([68, 63, 14, 67, 20, 79, 60, 74, 93, 35])

**Q2**

In [104]:
b = np.random.randint(-10,10,size=12).reshape(3,4)
b

array([[  2,  -7,  -9,  -7],
       [ -7,   8, -10,   2],
       [  1,   1,  -7,  -9]])

**Q3**

In [105]:
b.flatten()
# arr2.reshape(1,12)

array([  2,  -7,  -9,  -7,  -7,   8, -10,   2,   1,   1,  -7,  -9])

**Q4**

In [106]:
a_copy = a.copy()
a_copy[0] = -1
print(a_copy)
print(a)

[-1 63 14 67 20 79 60 74 93 35]
[68 63 14 67 20 79 60 74 93 35]


**Q5**

In [107]:
c = a[::2]
c

array([68, 14, 20, 60, 93])

**Q6**

In [108]:
print(a)
print(a[2])

[68 63 14 67 20 79 60 74 93 35]
14


**Q7**

In [109]:
print(b)
print("\n")
b[-1]

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]]




array([ 1,  1, -7, -9])

**Q8**

In [110]:
b[:2, -2:]

array([[ -9,  -7],
       [-10,   2]])

**Q9**

In [111]:
print(b)
print("\n")
b_row = b[1]
b_row

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]]




array([ -7,   8, -10,   2])

**Q10**

In [112]:
print(b)
print("\n")
b_col = b[:,0]
b_col

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]]




array([ 2, -7,  1])

**Q11**

In [113]:
d = np.linspace(1,10,10, dtype="int")
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Q12**

In [114]:
print(a,'\n')
print(d,'\n')
e = a+d
e

[68 63 14 67 20 79 60 74 93 35] 

[ 1  2  3  4  5  6  7  8  9 10] 



array([ 69,  65,  17,  71,  25,  85,  67,  82, 102,  45])

**Q13**

In [115]:
print(b,'\n')
# b_double = b*2
b_double = np.multiply(b,2)
b_double

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]] 



array([[  4, -14, -18, -14],
       [-14,  16, -20,   4],
       [  2,   2, -14, -18]])

**Q14**

In [116]:
print(b,'\n\n',b_double,'\n\n')
f = np.dot(b,b_double.transpose())
f

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]] 

 [[  4 -14 -18 -14]
 [-14  16 -20   4]
 [  2   2 -14 -18]] 




array([[366,  12, 242],
       [ 12, 434, 106],
       [242, 106, 264]])

**Q15**

In [117]:
a_mean = np.mean(a)
b_mean = np.mean(b)
b_double_mean = np.mean(b_double)

print(a_mean)
print(b_mean)
print(b_double_mean)

print('\n')

g = np.array([a_mean,b_mean,b_double_mean])
g

57.3
-3.5
-7.0




array([57.3, -3.5, -7. ])

**Q16**

In [118]:
a_sum = np.sum(a)
# for num in a:
#   a_sum += num
print(a_sum)

573


**Q17**

In [119]:
print(b,"\n")
b_min = np.min(b)
b_min

[[  2  -7  -9  -7]
 [ -7   8 -10   2]
 [  1   1  -7  -9]] 



np.int64(-10)

**Q18**

In [120]:
print(b_double,'\n')
b_double_max = np.max(b_double)
b_double_max

[[  4 -14 -18 -14]
 [-14  16 -20   4]
 [  2   2 -14 -18]] 



np.int64(16)